movie_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('movies.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('filter/', views.FilterMoviesView.as_view(), name="filter"),
    path('search/', views.Search.as_view(), name="search"),
    path('categories/', views.CategoriesList.as_view(), name="categories_list"),
    path('category/<str:slug>/', views.CategoryDetail.as_view(), name="category_detail"),
    path('add-rating/', views.AddStarRating.as_view(), name="add_rating"),
    path('json-filter/', views.JsonFilterMoviesView.as_view(), name="json_filter"),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name="movie_detail"),
    path('review/<int:pk>/', views.AddReview.as_view(), name="add_review"),
    path('actor/<str:slug>/', views.ActorView.as_view(), name="actor_detail"),
    path('', views.MoviesView.as_view(), name="movies_list"),
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class Category(models.Model):
    '''Категории'''
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = "Категория фильмов"
        verbose_name_plural = "Категории фильмов"


class Actor(models.Model):
    '''Актеры и режиссеры фильмов'''
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actor/")
    director = models.BooleanField("Режиссер", default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={'slug': self.name})

    class Meta:
        verbose_name = "Актер или режисер"
        verbose_name_plural = "Актеры и режисеры"


class Genre(models.Model):
    '''Жанры'''
    name = models.CharField("Наименование", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    '''Фильм'''
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2020)
    country = models.CharField("Страна", max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актер", related_name="film_actors")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premier = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="указать сумму в долларах США")
    fees_in_russia = models.PositiveIntegerField(
        "Сборы в РФ", default=0, help_text="указать сумму в долларах США"
    )
    fees_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указать сумму в долларах США"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={'slug': self.url})

    def get_reviews(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    '''Кадры из фильма'''
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Кадр", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    '''Звезда рейтинга'''
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    '''Рейтинг'''
    ip = models.CharField("IP адресс", max_length=20)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    '''Отзывы'''
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/forms.py
from django import forms

from .models import Reviews, RatingStar, Rating


class ReviewForm(forms.ModelForm):
    '''Форма отзыва'''
    class Meta:
        model = Reviews
        fields = ("name", "email", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }


class RatingForm(forms.ModelForm):
    '''Форма добавления рейтинга'''
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star", )

movies/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from django.http import HttpResponse, JsonResponse
from .models import Movie, Category, Actor, Genre, Rating
from .forms import ReviewForm, RatingForm
from django.db.models import Q



class GenreYear:
    '''Жанры и года выхода фильмов'''
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values("year")


class MoviesView(GenreYear, ListView):
    '''Список фильмов'''
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movies/movies.html"
    paginate_by = 4


class MovieDetailView(GenreYear, DetailView):
    '''Подробное описание фильма'''
    model = Movie
    slug_field = "url"
    template_name = "movies/moviesingle.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class AddReview(View):
    '''Отзыв'''
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    '''Отображение информации об актере'''
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    '''Фильтр фильмов'''
    template_name = 'movies/movies.html'
    paginate_by = 4

    def get_queryset(self):
        queryset = Movie.objects.filter(
            # OR
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))

            # AND
            #year__in=self.request.GET.getlist("year"), genres__in=self.request.GET.getlist("genre")
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class JsonFilterMoviesView(ListView):
    '''Фильтр фильмов в JSON'''
    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({'movies': queryset}, safe=False)


class AddStarRating(View):
    '''Добавление рейтинга фильму'''
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip = self.get_client_ip(request),
                movie_id = int(request.POST.get("movie")),
                defaults = {'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(ListView):
    '''Поиск фильмов'''
    template_name = "movies/movies.html"
    paginate_by = 4

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context


class CategoriesList(ListView):
    '''Список категорий'''
    model = Category
    template_name = "movies/categories.html"
    queryset = Category.objects.all()
    paginate_by = 4


class CategoryDetail(DetailView):
    '''Описание категорий'''
    model = Category
    template_name = "movies/category.html"
    slug_field = "url"

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}

{% block title %} {{ actor.name }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ actor.name }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span>
                    </li>
                    <li>
                        <span><b>Режиссер в фильмах:</b><br>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}<br>
                            {% endfor %}
                        </span>
                    </li>
                    <li>
                        <span><b>Актер в фильмах:</b><br>
                            {% for movie in actor.film_actors.all %}
                                {{ movie.title }}<br>
                            {% endfor %}
                        </span>
                    </li>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                Информация о {{ actor.name }}</h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}

{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
                {% block container %}
                    <div class="container-fluid py-md-3">
                {% endblock container %}
                        <div class="row">
                            {% block sidebar %}
                                <div class="side-bar col-lg-3">
                            {% endblock sidebar %}
                                    {% include 'include/sidebar.html' %}
                                </div>
                            {% block movie %}
                            {% endblock movie %}
                            {% block categories %}
                            {% endblock categories %}
                        </div>
                    </div>
    </section>
{% endblock content %}

templates/movies/categories.html
{% extends 'movies/base.html' %}

{% block categories %}
<div class="row">
    <div class="desc1-right col-md-10 pl-lg-4">
        <h1 class="editContent" style="outline: none; cursor: inherit;">
            {% for category in category_list %}
                    <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            {% endfor %}
        </h1>
    </div>
</div>
{% endblock categories %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="/categories/" class="editContent">Категории</a></li>
{% endblock %}

templates/movies/category.html
{% extends 'movies/base.html' %}
{% load static %}

{% block title %} {{ actor.name }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="ml-5">
        <div class="row">
            <div>
                <h1 class="editContent">
                    {{ category.name }}
                </h1>
                <ul>
                    <li>
                        <span><b>Описание:</b> {{ category.description }} </span>
                    </li>
                    <li>
                        <span><b>Фильмы в категории:</b><br>
                            {% for movie in category.movie_set.all %}
                                <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a><br>
                            {% endfor %}
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                Информация о категории {{ category.name }}</h3>
        </div>
            <p class="editContent">
                {{ category.description|safe }}
            </p>
        
    </div>
{% endblock movie %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{{ category.get_absolute_url }}" class="editContent">О категории {{ category.name }}</a></li>
{% endblock %}

templates/movies/movies.html
{% extends 'movies/base.html' %}

    {% block header %}bg1{% endblock header %}
    {% block movie %}
        <div class="left-ads-display col-lg-9">
            <div class="row">
                {% for movie in movie_list %}
                    <div class="col-md-4 product-men">
                        <div class="product-shoe-info editContent text-center mt-lg-4" >
                            <div class="men-thumb-item">
                                <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                            </div>
                            <div class="item-info-product">
                                <h4 class="">
                                    <a href="{{ movie.get_absolute_url }}" class="editContent" >{{ movie.title }}</a>
                                </h4>

                                <div class="product_price">
                                    <div class="grid-price">
                                        <span class="money editContent" >{{ movie.tagline }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div style="margin-top: 40px;">
                {% include 'include/pagination.html' %}
            </div>
        </div>
    {% endblock movie %}

templates/movies/moviesingle.html
{% extends 'movies/base.html' %}

{% load static %}

{% block title %} {{ movie.title }} {% endblock title %}

{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
        <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
            <div class="left-ads-display col-lg-8">
                <div class="row">
                    <div class="desc1-left col-md-6">
                        <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                    </div>
                    <div class="desc1-right col-md-6 pl-lg-4">
                        <h3 class="editContent" style="outline: none; cursor: inherit;">
                            {{ movie.title }}
                        </h3>
                        <h5 class="editContent"></h5>
                        <ul>
                            <li>
                                <span><b>Год:</b>{{ movie.year }}</span>
                            </li>
                            <li>
                                <span><b>Страна:</b>{{ movie.country }}</span>
                            </li>
                            <li>
                                <span><b>Слоган:</b>{{ movie.tagline }}</span>
                            </li>
                            <li>
                                <span><b>Режиссер:</b>
                                    {% for director in movie.directors.all %}
                                        <a href="{{ director.get_absolute_url }}">{{ director.name }}</a>
                                    {% endfor %}
                                </span>
                            </li>
                            <li>
                                <span><b>Актеры:</b>
                                    {% for actor in movie.actors.all %}
                                        <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a><br>
                                    {% endfor %}
                                </span>
                            </li>
                            <li>
                                <span><b>Жанр:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                </span>
                            </li>
                            <li>
                                <span><b>Премьера в мире:</b>{{ movie.world_premier }}</span>
                            </li>
                            <li>
                                <span><b>Бюджет:</b>$ {{ movie.budget }}</span>
                            </li>
                            <li>
                                <span><b>Сборы в РФ:</b>$ {{ movie.fees_in_russia }}</span>
                            </li>
                            <li>
                                <span><b>Сборы в мире:</b>$ {{ movie.fees_in_world }}</span>
                            </li>
                            <li>
                                <form action="{% url 'add_rating' %}" method="post" name="rating">
                                    <b>Рейтинг:</b>
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ request.path }}" name="next">
                                    <input type="hidden" value="{{ movie.id }}" name="movie">
                                    <span class="rating">
                                        {% for k, v in star_form.fields.star.choices %}
                                            <input type="radio" name="star" id="rating{{ v }}" value="{{ k }}">
                                            <label for="rating{{ v }}">{{ k }}</label>
                                        {% endfor %}
                                    </span>
                                    <span class="editContent">{{ movie.rating_set.get.star }}</span>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row sub-para-w3layouts mt-5">
                    <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                        О фильме {{ movie.title }}
                    </h3>
                    <p>
                        {% for image in movie.movieshots_set.all %}
                            <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
                        {% endfor %}
                    </p>
                    <p class="editContent">
                        {{ movie.description|safe }}
                    </p>
                </div>
                <hr>
                <div class="row">
                    <div class="single-form-left">
                        <!-- contact form grid -->
                        <div class="contact-single">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                <span class="sub-tittle editContent"
                                        style="outline: none; cursor: inherit;">{{ movie.reviews_set.count }}</span>Оставить отзыв</h3>
                            <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                                {% csrf_token %}
                                <input type="hidden" name="parent" id="contactparent" value="">
                                <div class="form-group editContent"
                                    <label for="contactcomment" class="editContent">
                                            Ваш комментарий*
                                    </label>
                                    {{ form.text }}
                                </div>
                                <div class="d-sm-flex">
                                    <div class="col-sm-6 form-group p-0 editContent"
                                        <label for="contactusername" class="editContent">
                                                Имя*
                                        </label>
                                        {{ form.name }}
                                    </div>
                                    <div class="col-sm-6 form-group ml-sm-3 editContent"
                                        <label for="contactemail" class="editContent">
                                                Email*
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <button type="submit"
                                        class="mt-3 btn btn-success btn-block py-3">
                                        Отправить
                                </button>
                            </form>
                        </div>
                        <!--  //contact form grid ends here -->
                    </div>
                </div>
                    {% for review in movie.get_reviews %}
                        <div class="media py-5">
                            <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent">
                                    {{ review.name }}
                                </h5>
                                <p class="mt-2 editContent">
                                    {{ review.text }}
                                </p>
                                <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                                {% for rew in review.reviews_set.all %}
                                    <div class="media mt-5 editContent">
                                        <a class="pr-3" href="#">
                                            <img src="{% static 'images/te1.jpg' %}" class="img-fluid " alt="image">
                                        </a>
                                        <div class="media-body">
                                            <h5 class="mt-0 editContent">{{ rew.name }}</h5>
                                            <p class="mt-2 editContent">{{ rew.text }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function addReview(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomment").innerText = `${name}, `
        }
    </script>
{% endblock movie %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{{ movie.get_absolute_url }}" class="editContent">О фильме {{ movie.title }}</a></li>
{% endblock %}